
project_id = "kytqqjnecezkxyhmmjrz"

[functions.verifierCodeAcces]
verify_jwt = false

[functions.accessSharedProfile]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false

[functions.auth-hooks]
verify_jwt = false

[db.webhooks.auth_hooks]
enabled = true
url = "https://kytqqjnecezkxyhmmjrz.supabase.co/functions/v1/auth-hooks"
events = ["auth.users.insert", "auth.users.update"]
