
project_id = "kytqqjnecezkxyhmmjrz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000

[db]
port = 54322
shadow_port = 54320
major_version = 15
max_connections = 200

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "100MiB"
image_transformation = {enabled = true}

[auth]
enabled = true
port = 54326
site_url = "https://www.directivesplus.fr"
additional_redirect_urls = ["https://www.directivesplus.fr", "http://localhost:3000", "https://24c30559-a746-463d-805e-d2330d3a13f4.lovableproject.com"]
jwt_expiry = 7200
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true
enable_confirmations = true
password_min_length = 8
password_requirements = ["lowercase", "uppercase", "numbers"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m"

# Configuration pour supporter des milliers d'inscriptions
[auth.rate_limits]
signup = {period = "1h", requests = 100}
signin = {period = "1m", requests = 60}
password_reset = {period = "1h", requests = 30}
email_change = {period = "1h", requests = 10}

[edge_functions]
enabled = true
port = 54327

[functions.send-sms-code]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-twilio-sms]
verify_jwt = false

[functions.send-auth-code]
verify_jwt = false

[analytics]
enabled = true

# Configuration pour la performance
[performance]
statement_timeout = "30s"
idle_in_transaction_session_timeout = "10m"
