// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxytckmvmvtfcihnhlbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eXRja212bXZ0ZmNpaG5obGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MzkzNjUsImV4cCI6MjA1MjExNTM2NX0.JryqQCXMlpsZTu6n_00uCNc6POpYp4Ng5TsbnlbSHOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);